{% set name = "google-analytics-admin" %}
{% set version = "0.22.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fdc503ad6c18c91317c8a7ac1479ff5feb5750e03b8c2d760089c195898c5361

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    - proto-plus >=1.22.3,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.analytics.admin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-analytics-admin
  summary: Google Analytics Admin API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-analytics-admin
  doc_url: https://googleapis.dev/python/analyticsadmin/latest/

extra:
  recipe-maintainers:
    - xylar
